name: aplicacion_conductores
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+7

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  permission_handler: ^11.3.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_auth_web: ^5.0.0
  firebase_messaging: ^15.2.2
  cloud_firestore: ^5.6.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.1
  intl: ^0.18.0
  image_picker: 1.0.4                # ✅ Versión compatible con SDK 34
  lottie: ^2.6.0
  path_provider: ^2.0.2
  local_auth: ^2.1.6
  local_auth_android: ^1.0.34
  flutter_html: ^3.0.0
  flutter_animate: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/2022cercetafinal_blanco.png"
  remove_alpha_ios: true
