// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgd-BJyZsX5iijO-v7HRUPXy-ZOCkA3LM',
    appId: '1:682756534988:web:e39a9bc9705667e2c70869',
    messagingSenderId: '682756534988',
    projectId: 'cercetaapk',
    authDomain: 'cercetaapk.firebaseapp.com',
    storageBucket: 'cercetaapk.firebasestorage.app',
    measurementId: 'G-17ZZEC57LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLyp_VaCw2ND4PUqp2rXJiCS3Ocj-jIqI',
    appId: '1:682756534988:android:e942fb032f42f030c70869',
    messagingSenderId: '682756534988',
    projectId: 'cercetaapk',
    storageBucket: 'cercetaapk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCent3pzumK4eyXXel5q92lpO1kyNHrxY',
    appId: '1:682756534988:ios:3cbf97fddd93f85cc70869',
    messagingSenderId: '682756534988',
    projectId: 'cercetaapk',
    storageBucket: 'cercetaapk.firebasestorage.app',
    iosBundleId: 'app.cercetaresidencial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCent3pzumK4eyXXel5q92lpO1kyNHrxY',
    appId: '1:682756534988:ios:d9d0ebfd5441a426c70869',
    messagingSenderId: '682756534988',
    projectId: 'cercetaapk',
    storageBucket: 'cercetaapk.firebasestorage.app',
    iosBundleId: 'com.example.viancoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgd-BJyZsX5iijO-v7HRUPXy-ZOCkA3LM',
    appId: '1:682756534988:web:b4adae6f9e1c5850c70869',
    messagingSenderId: '682756534988',
    projectId: 'cercetaapk',
    authDomain: 'cercetaapk.firebaseapp.com',
    storageBucket: 'cercetaapk.firebasestorage.app',
    measurementId: 'G-20ZN6SWJD7',
  );
}
