// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDziU2t5kSnu7YqT5LBh8Fwr94Xj8Sdig4',
    appId: '1:837635390811:web:edd25bfb7d42755f48ae7e',
    messagingSenderId: '837635390811',
    projectId: 'cercetaaplicacion',
    authDomain: 'cercetaaplicacion.firebaseapp.com',
    storageBucket: 'cercetaaplicacion.firebasestorage.app',
    measurementId: 'G-ZCBMGGMWFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCLTgJL77BI7jifhrMXsa5G5rRqaIcck',
    appId: '1:837635390811:android:116e7d6207e8574c48ae7e',
    messagingSenderId: '837635390811',
    projectId: 'cercetaaplicacion',
    storageBucket: 'cercetaaplicacion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJghb2QCRy_EQtjC9wEhXjCmJI_leqDg',
    appId: '1:837635390811:ios:f645cd94df48a4e148ae7e',
    messagingSenderId: '837635390811',
    projectId: 'cercetaaplicacion',
    storageBucket: 'cercetaaplicacion.firebasestorage.app',
    iosBundleId: 'app.cercetaresidencial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJghb2QCRy_EQtjC9wEhXjCmJI_leqDg',
    appId: '1:837635390811:ios:e941c41f5fadb2a348ae7e',
    messagingSenderId: '837635390811',
    projectId: 'cercetaaplicacion',
    storageBucket: 'cercetaaplicacion.firebasestorage.app',
    iosBundleId: 'com.example.viancoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDziU2t5kSnu7YqT5LBh8Fwr94Xj8Sdig4',
    appId: '1:837635390811:web:d493fc79c65c677248ae7e',
    messagingSenderId: '837635390811',
    projectId: 'cercetaaplicacion',
    authDomain: 'cercetaaplicacion.firebaseapp.com',
    storageBucket: 'cercetaaplicacion.firebasestorage.app',
    measurementId: 'G-4EDLWQKHVX',
  );
}
